// https://icones.js.org/

export enum IconIds {
    CHEVRON_DOWN = 'carbon:chevron-down',
    CHEVRON_UP = 'carbon:chevron-up',
    CHEVRON_RIGHT = 'carbon:chevron-right',
    CHEVRON_LEFT = 'carbon:chevron-left',
    DOUBLE_CHEVRON_LEFT = 'mdi-light:chevron-double-left',
    DOUBLE_CHEVRON_RIGHT = 'mdi-light:chevron-double-right',
    OVERFLOW_MENU_VERTICAL = 'carbon:overflow-menu-vertical',
    CLOSE = 'carbon:close',
    SEARCH = 'carbon:search',
    COPY = 'carbon:copy',
    CHECKMARK = 'carbon:checkmark',
    DOWNLOAD = 'carbon:download',
    UPDATE_NOW = 'carbon:update-now',
    CLOUD_UPLOAD = 'carbon:cloud-upload',
    REPORT = 'carbon:report-data',
    ARROW_RIGHT = 'carbon:arrow-right',
    IC_OUTLINE_CALENDAR_MONTH = 'ic:outline-calendar-month',
    IC_OUTLINE_MODE_EDIT = 'ic:outline-mode-edit',
    // IC_BASELINE_OPEN_IN_NEW = 'ic:baseline-open-in-new',
    IC_BASELINE_OPEN_IN_NEW = 'carbon:arrow-up-right',
    THEME_LIGHT = 'line-md:sunny-filled-loop',
    THEME_DARK = 'line-md:sunny-filled-loop-to-moon-filled-alt-loop-transition',
    X = 'ri:twitter-x-fill',
    TELEGRAM = 'ph:telegram-logo',
    TELEGRAM_LOGO = 'logos:telegram',
    WEBSITE = 'mdi:web',
    DISCORD = 'mdi:discord',
    GITHUB = 'mdi:github',
    LINKEDIN = 'mdi:linkedin',
    TRANSACTION = 'carbon:text-align-center',
    CONTRACT = 'carbon:cics-program',
    LOADING_DOTS = 'LOADING_DOTS',
    CRYPTO_BTC = 'cryptocurrency-color:btc',
    CRYPTO_ETH = 'cryptocurrency-color:eth',
}
